logging:
  level:
    org.springframework.web: INFO
    be.wouterversyck.marcusapi: INFO

spring:
  jpa:
    open-in-view: false
  liquibase:
    contexts: default
server:
  servlet:
    context-path: /api
  error:
    include-stacktrace: on_trace_param

jwt:
  secret-key: ${jwt.secret}
  auth-login-url: /login
  token-header: Authorization
  response-token-header: x-token
  token-prefix: Bearer
  token-type: JWT
  token-issuer: secure-api
  token-audience: secure-app
  # 12 hours in millis
  expiration: 43200000
  google-client-id: 346054450113-nb0l4atr9h6r9s3rmfli7u75ep5pl3be.apps.googleusercontent.com

mdc:
  correlation-id-header-key: x-correlation-id
  user-mdc-key: user
  correlation-id-mdc-key: correlationId

mail:
  smtp-username: ${mail.user}
  smtp-password: ${mail.pwd}
  smtp-host: smtp.gmail.com
  smtp-port: 587
  smtp-auth: true
  smtp-start-ttls: true
