logging:
  config: classpath:logging/logback-prd.xml

server:
  servlet:
    context-path: /marcus/api

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      uri: ${mongo.srv}
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      jdbc-url: ${spring.datasource.url}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
